# Generated by Django 4.0.5 on 2022-07-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_published',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
